# -*- coding: utf-8 -*-
"""Task1_Lab4_Arcera

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AzUKEH-Q6gENUZg_fO5HK1lLU-tSLhlb

# **Task 1**
"""

VectorE = [(8,3,9,5)]
VE = []

for numbers in VectorE:
    for number in numbers:
        sqrt = number **2
        VE.append(sqrt)

VectorA = [(24,25,23,27)]
VA = []


for numbers in VectorA:
    for number in numbers:
        sqrt = number **2
        VA.append(sqrt)


VectorL = [(19,19,24,25)]
VL = []


for numbers in VectorL:
    for number in numbers:
        sqrt = number **2
        VL.append(sqrt)    

VectorP = [(11,15,26,28)]
VP = []

for numbers in VectorP:
    for number in numbers:
        sqrt = number **2
        VP.append(sqrt) 

VectorC = [(14,13,29,24)]
VC = []

for numbers in VectorC:
    for number in numbers:
        sqrt = number **2
        VC.append(sqrt) 

VectorS = [(17,12,32,38)]
VS = []


for numbers in VectorS:
    for number in numbers:
        sqrt = number **2
        VS.append(sqrt) 

## Vector E
print('Given:                       ',VectorE)
print('The square of all numbers    ',VE)
print('The sum of all numbers:      ',sum(VE))
print('The square root of the sum:  ',sum(VE)**(1/2))
print('*'*66)
print('')

#Vector A
print('Given:                       ',VectorA)
print('The square of all numbers    ',VA)
print('The sum of all numbers:      ',sum(VA))
print('The square root of the sum:  ',sum(VA)**(1/2))
print('*'*66)
print('')

#Vector L
print('Given:                       ',VectorL)
print('The square of all numbers    ',VL)
print('The sum of all numbers:      ',sum(VL))
print('The square root of the sum:  ',sum(VL)**(1/2))
print('*'*66)
print('')

#Vector P
print('Given:                       ',VectorP)
print('The square of all numbers    ',VP)
print('The sum of all numbers:      ',sum(VP))
print('The square root of the sum:  ',sum(VP)**(1/2))
print('*'*66)
print('')

#Vector C
print('Given:                       ',VectorC)
print('The square of all numbers    ',VC)
print('The sum of all numbers:      ',sum(VC))
print('The square root of the sum:  ',sum(VC)**(1/2))
print('*'*66)
print('')

#Vector S
print('Given:                       ',VectorS)
print('The square of all numbers    ',VS)
print('The sum of all numbers:      ',sum(VS))
print('The square root of the sum:  ',sum(VS)**(1/2))
print('*'*66)
print("")