# -*- coding: utf-8 -*-
"""Task3_Lab4_Arcera

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vDXvISwp7Wcs2Ut_FiQdKciXU9igz4VW

# **Task 3**
"""

import numpy as np
import matplotlib.pyplot as plt

a= np.array([-0.4 , 4.3 , -0.6 ])
b = np.array([-0.2 , 0.2, 1])
c = np.array([-0.2, 2.1, -1.5])

plt.xlim(-4,8)
plt.ylim(5,6.4)

answer = ((np.square(a) + np.square(b) + np.square(c)) * (np.divide(np.multiply(a,(np.add(b, (np.multiply(a,b))))),c)))*(np.linalg.norm(a+b+c))
print('(A**2 + B**2 + C**2)*(A*(B+A*B)/C)*||A + B + C||=',answer)

print('*'*100) 

plt.quiver(a[0], a[1], b[0], b[1], angles='xy', scale_units='xy',
           scale=1, color='red')
plt.quiver(a[0] + b[0], a[1] + b[1], c[0], c[1], angles='xy', scale_units='xy',
           scale=1, color='purple')
d = b + c
plt.quiver(a[0], a[1], d[0], d[1] ,angles='xy', scale_units='xy',
           scale=1, color='yellow')

R_mag = np.sqrt(np.sum(b**2+c**2))
rise = c[1]
run = c[0]
slope = rise/run
print('The slope is: ',slope)
plt.xlim(-5,9)
plt.ylim(4,7.5)
plt.grid()
plt.legend()
plt.show()

"""**Task 3**"""